services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    environment:
      - POSTGRES_USER=bookstore_dev
      - POSTGRES_PASSWORD=bookstore_dev
      - POSTGRES_DB=bookstore_dev_db
    networks:
      - backend
# Configuração network
networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
